CREATE TABLE el_user (
	ID VARCHAR ( 36 ) NOT NULL,
	created_at 			TIMESTAMP,
	created_by 			VARCHAR ( 36 ),
	last_modified_at 	TIMESTAMP,
	last_modified_by 	VARCHAR ( 36 ),
	VERSION int4 		NOT NULL,
	username 			VARCHAR(100) NOT NULL UNIQUE,
	password			VARCHAR(255) NOT NULL,
	display_name		VARCHAR(255) NOT NULL,
	first_name			VARCHAR(100),
	last_name			VARCHAR(100),
	email				VARCHAR(100) NOT NULL UNIQUE,
	avatar				VARCHAR(255),
	status				VARCHAR(50) NOT NULL,
	department			VARCHAR(255),
	major				VARCHAR(255),
	hobbies				VARCHAR(255),
	facebook			VARCHAR(255),
	PRIMARY KEY ( ID ) 
);